### ISSUE TITLE
Add spell check to "value has no .f field" errors

### ISSUE THREAD

**Issue by alandonovan** [google/starlark-go#135]
It would help the user if when a field name x.foo is mistyped, the error message gives a hint as to the correct name (did you mean food?). Since we're already producing an error, performance is not really an issue. The challenge is to do it without adding a dependency on a Levenshtein or Soundex package.

**Comment by laurentlb** [comment]
Writing a Levenshtein implementation is simple.
I wrote this one in Bazel: https://github.com/bazelbuild/bazel/blob/71b4dcc1e9a86e922b2f9a0a0665627ffd5233c8/src/main/java/com/google/devtools/build/lib/util/SpellChecker.java

**Comment by alandonovan** [comment]
Thanks!

**Comment by adonovan** [comment]
I think NoSuchFieldError needs to be a type of error, not a value, so that implementations of SetField can both return an error message and indicate that they would like the message to be augmented by spell checking.  See starlarkstruct.Struct for an example of a type I should have tested this on. :(
