### ISSUE TITLE
hash("") and hash(False) are both 0

### ISSUE THREAD

**Issue by josharian** [google/starlark-go#162]
There's nothing technically wrong with this, but zero hash values smell funny. `hash(0)` is non-zero.

```
$ starlark
Welcome to Starlark (go.starlark.net)
>>> hash(0)
37748751
>>> hash("")
0
>>> hash(False)
0
```

**Comment by josharian** [comment]
Actually, I can see the case for `hash(False) == 0`. The empty string seems weirder. An easy fix would be to throw the string length into the hash function as well as the bytes. If you care about fixing it.

**Comment by alandonovan** [comment]
The Java implementation of hash accepts only strings, and though I long thought that was an oversight---hashing is a key concept in the spec, why not expose it?---I recently learned from laurentlb that it was intentional: without the `hash` built-in, the hash function of each data type does not visibly affect program execution. (Hash tables iteration order is determined by insertion order, not hash values.) The `hash` builtin thus makes observable program behavior dependent on the hash functions, which would presumably inevitably vary across implementations. Thus different implementations of the language would produce different executions of the same program, which violates a design goal.

That said, there are many other observable differences, such as the UTF-8/16 difference in len(str), the type(function) string, and so on.

@laurentlb

**Comment by alandonovan** [comment]
`hash` now accepts only strings. It is specified as such, and the Go and Java implementations agree. Closing.
