### ISSUE TITLE
starlark: enumerate Thread.locals

### ISSUE THREAD

**Issue by silas** [google/starlark-go#228]
I'm writing a tool that inspects starlark files and does [pytest][pytest] style dependency injection. In order to accomplish this I need access to loaded function signatures and aliased names.

It doesn't seem possible to get this information without setting `resolve.LoadBindsGlobally = true` (#185), an option that is deprecated.

Would you be opposed to adding a method to enumerate Thread.locals or in some other way expose loaded names/aliases?

Obviously I have a work around right now, I just wanted to see if I could get a solution in place before `LoadBindsGlobally` goes away.

## Example Usage

``` python
load("./helpers.star", "setup_local", setup_remote="setup_gcs")

def task1(setup_local, setup_remote):
    pass

def test2(task1):
    pass
```

In the above example `task2` depends on `task1` and `task1` depends on `setup_local` + `setup_remote`/`setup_gcs`.

[pytest]: https://docs.pytest.org/en/latest/fixture.html

**Comment by alandonovan** [comment]
First, LoadBindsGlobally may be around longer than I anticipated, because it is required by the REPL, in which each compound statement is treated as its own "file" by the resolver, so if load creates file-local bindings, you can't see them on the next statement. This was a regression of #178, fixed in #226 by re-enabling that flag in the REPL.

Second, I don't think Thread.locals is what you want. Thread locals holds the "thread-local variables" of a Starlark thread; that is, values belonging to the host application that are associated with the thread at creation and accessible by built-in functions. It is not the Starlark local variables of each function call; these live in Thread.stack, which is the stack of frames of active function calls. Thread.stack is not intended to be used by most clients, but some tools (such as debuggers) need access to local variables, so there is an API.  Thread.DebugFrame(i) returns the ith enclosing call frame, and DebugFrame.Local(i) returns the value of that local variable. You can use Function.Param to describe the first NumParams local variables corresponding to the functions's parameters; for the remaining locals there is no API to access their name and position. (Now that I look I see that this function does not check that i < NumParams, but it should, so please don't abuse it.) Perhaps this will suffice for your needs.

P.S. for what project are you using Starlark?

**Comment by alandonovan** [comment]
P.P.S. your example seems to be a domain-specific language embedded within Starlark in which the name of the parameter task1 in function task2 is interpreted as a dependency from function task2 to a function task1. It's not really an ordinary function. This seems to me like a metaprogramming hack. A simpler and clearer approach would be to do what bazel does, and rely on ordinary evaluation to build and express a dependency structure. For example:
```
task(name = "task1", ...)
task(name = "task2", deps = ["task1"], ...)
```
Or perhaps:
```
task1 = task(...)
task2 = task(..., deps=[task1])
```

**Comment by silas** [comment]
@alandonovan Thanks for taking the time to respond. I agree, I could use a much simpler interface and just be done with it.

That being said, one of the goals of the project is to keep the syntax relatively terse (on par with something like make), so I'm committed to my interface for the time being.

Digging a bit more into the code it looks like the data I want lives in `go.starlark.net/internal/compile.Program.Names` and doesn't seem to be exposed anywhere, but I definitely could have missed something.

I'll just keep using `LoadBindsGlobally` for now. My use case seems pretty far outside of the normal path and probably isn't worth exposing any more internals for.

If you're curious, a minimal version of what I'm currently doing is below (or via the [Playground][playground]):

``` go
package main

import (
	"fmt"

	"go.starlark.net/resolve"
	"go.starlark.net/starlark"
)

func init() {
	resolve.LoadBindsGlobally = true
}

func load(thread *starlark.Thread, module string) (starlark.StringDict, error) {
	return eval(module, `
def outside():
  pass

def outside2(outside):
  pass
	`)
}

func main() {
	globals, err := eval("main.star", `
load("example.star", "outside", alias="outside2")

def inside(alias):
  pass

def test(inside):
  pass
	`)
	if err != nil {
		panic(err)
	}

	for _, v := range globals {
		if v, ok := v.(*starlark.Function); ok {
			fmt.Println(v.Name())
			for i := 0; i < v.NumParams(); i++ {
				param, _ := v.Param(i)
				fmt.Println(" - ", param)
			}
		}
	}
}

func eval(name, src string) (starlark.StringDict, error) {
	thread := &starlark.Thread{
		Name: name,
		Load: load,
	}
	return starlark.ExecFile(thread, fmt.Sprintf("<%s>", name), src, nil)
}
```

`resolve.LoadBindsGlobally = true`

```
test
 -  inside
outside
outside2
 -  outside
inside
 -  alias
```

`resolve.LoadBindsGlobally = false`

```
inside
 -  alias
test
 -  inside
```

[playground]: https://play.golang.org/p/k5RVwkIv2qi

**Comment by alandonovan** [comment]
> I agree, I could use a much simpler interface and just be done with it.
> That being said, one of the goals of the project is to keep the syntax relatively terse (on par with something like make), so I'm committed to my interface for the time being.

The problem with that approach is that, not only are the semantics misleading to anyone who looks at the code and thinks "I know Python!", but eventually you'll want to add more information into the structure and there will be no place to put it, because you can't change the syntax of the language. If you use values to represent your structure, it will be easy to extend.
