### ISSUE TITLE
Implementation of Namespace

### ISSUE THREAD

**Issue by finn-ball** [google/starlark-go#274]
Hey,

In the Java implementation, there is a Namespace parameter:

https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/skylarkbuildapi/StarlarkAttrModuleApi.java#L39

If I'm understanding this correctly, this allows you to use a `Builtin` like this in Starlark:
``` python
attr.Label(default="//some/target:path")
```

Is there such a mechanism in the Go implementation? A quick parse of the source indicates not:
https://github.com/google/starlark-go/blob/master/starlark/value.go#L660

**Comment by alandonovan** [comment]
All `namespace` does is change the message printed by `str(attr)` so that it includes the suffix " (a language module)". I don't know why the Java implementation has that feature; it really doesn't carry its weight.

In the Go implementation, it's easy to construct a value that has fields like attr: simply implement the HasFields interface. See these examples:

starlarkstruct.Struct: https://github.com/google/starlark-go/blob/6ddc71c0ba77217b518c586dc8589d627c92ebfb/starlarkstruct/struct.go#L209
starlarkstruct.Module: https://github.com/google/starlark-go/blob/6ddc71c0ba77217b518c586dc8589d627c92ebfb/starlarkstruct/module.go#L21
