### ISSUE TITLE
[feature request] while statement

### ISSUE THREAD

**Issue by aarzilli** [google/starlark-go#36]
As discussed [here](https://github.com/derekparker/delve/issues/1415#issuecomment-441379775) I'd like to have a `while` statement in the language, guarded by a global flag. The discussion in that issue suggests using the for statement but I don't think that's possible since the `in` operator makes it ambiguous.

If this is acceptable, I can try implementing this myself.

**Comment by alandonovan** [comment]
Good point, I had forgotten about the ambiguity.  Fortunately the spec reserves the 'while' keyword so this is a compatible change.

Please add a flag, resolve.AllowRecursion, and make the resolver reject while loops unless this flag is set.  Also, please make the recursion check in the evaluator subject to this condition.  It will need tests and a spec change, with which I can help.

Thanks for the offer; a number of users have independently requested this.

**Comment by dgryski** [comment]
Should this be filed at https://github.com/bazelbuild/starlark instead ?

**Comment by alandonovan** [comment]
If you like, but it is unlikely to be accepted because the spec must serve the needs of Bazel, which does not want arbitrary recursion, and the maintainers of bazelbuild/starlark are unlikely to be interested in dialect options since it defeats the purpose of a central spec.  I have no problem adding dialect options to the Go implementation (withing reason) if it makes the project much more useful, so long as there is some set of options that causes it to conform to the bazelbuild/starlark spec. (See float, lambda, set, ...)

**Comment by laurentlb** [comment]
It's useful to file it on https://github.com/bazelbuild/starlark
This allows us to get the feedback in one place and gauge interest. If multiple implementations want to support this as an extension, they can also synchronize there.

**Comment by jammiess** [comment]
I've been looking through the docs to figure out if this feature can be enabled when the interpreter is embedded in a go program but haven't been able to find anything.
Is there are way to enable this feature through the go library api?

**Comment by MonicaRJones** [comment]
@jammiess  Set [resolve.AllowRecursion](https://godoc.org/go.starlark.net/resolve#AllowRecursion) to `true`.
