### ISSUE TITLE
API: add way to return error, which got during iteration

### ISSUE THREAD

**Issue by tdakkota** [google/starlark-go#366]
Current iterator API
https://github.com/google/starlark-go/blob/74c10e2c17dcdb1cd5ff8044e33d9338820db233/starlark/value.go#L238-L244
does not allow to return error, which got during iteration.

As I understand, Java implementation uses exception to pass errors.
https://github.com/bazelbuild/bazel/blob/f78ffb5fb2f37d20acd1320ed37080c26b32e607/src/main/java/net/starlark/java/eval/Eval.java#L118-L119

I think Go implementation can provide a special interface like
```go
type ErrIterator interface {
       Iterator
       Err() error
}
```

Example usage:
```go
iter := iterable.Iterator()
defer iter.Done()
var x Value
for iter.Next(&x) {
      ...
}
if errIter, ok := iter.(ErrIterator); ok {
	if err := errIter.Err(); err != nil {
		return err
	}
}
```

**Comment by adonovan** [comment]
While the proposed change would not cause any existing program not to compile, it is a semantically breaking change to the contract of an existing interface. That is, every place that currently calls Iterator.Done would become responsible for checking whether the iterator implements ErrIterator and handling the result of the Err method if so; failure to do so would cause errors to be silently ignored.

**Comment by AlekSi** [comment]
Okay, but then how do you return an error from an iterator? In our case, iterations happen over the results generated by the host. Errors are possible there. I think extending the iterator "protocol" to return an error is worth doing.

One option is to define a separate type/interface with a method to get an error. But then the interpreter should be forked to check for that interface in the implementation of the `for` loop.

Is there a better option?

EDIT: Well, yes, I overlooked the obvious one: do the same as, for example, Go's [`sql.Rows`](https://pkg.go.dev/database/sql#Rows) – have a [separate method](https://pkg.go.dev/database/sql#Rows.Err) to be checked after iteration.

**Comment by adonovan** [comment]
> Okay, but then how do you return an error from an iterator? In our case, iterations happen over the results generated by the host. Errors are possible there. I think extending the iterator "protocol" to return an error is worth doing.
> 
> One option is to define a separate type/interface with a method to get an error. But then the interpreter should be forked to check for that interface in the implementation of the `for` loop.
> 
> Is there a better option?
> 
> EDIT: Well, yes, I overlooked the obvious one: do the same as, for example, Go's [`sql.Rows`](https://pkg.go.dev/database/sql#Rows) – have a [separate method](https://pkg.go.dev/database/sql#Rows.Err) to be checked after iteration.

Starlark has extremely limited support for handling errors in general. This makes sense in the context of its origin as a configuration language, in which programs are short lived and tend to build up data values using pure computation, and peek and poke the state of some host application (e.g. Bazel) again using pure data. Using Starlark in context where it performs I/O (such as file system operations or HTTP requests) directly highlights the need for error-handling features that it does not currently have. This problem should probably be attacked holistically rather than piecemeal.


In general you can follow Go's approach of returning a pair of (value, error) and requiring explicit checks. The lack of a type system does make this painful. (BTW the Starlark-Rust implementation has [optional types](https://github.com/facebook/starlark-rust/blob/main/docs/types.md), and there have been recent rumblings suggesting that the Starlark-Java implementation in Bazel is gearing up for a types proposal such as https://github.com/bazelbuild/starlark/issues/106.)

**Comment by AlekSi** [comment]
Thank you. There is also an interesting discussion about iterators and errors in Go: https://github.com/golang/go/issues/71901. Linking it for future readers.
