### ISSUE TITLE
FR: json.valid

### ISSUE THREAD

**Issue by apeabody** [google/starlark-go#465]
As Starlark doesn't include `try` and `except`, it would be valuable to have a `json.valid` or similar function to enable custom handling (overwrite, `fail`, etc) of invalid json encoding.

**Comment by adonovan** [comment]
There's a general question here of how to support errors. One approach is "look before you leap", which means calling `json.valid` before `json.decode`. The problem is that in general it is twice as expensive in the common case. Also, there's a risk of skew between the two operations so that valid returns true but decode still fails. The alternative approach is to pass an additional argument that requests fault-tolerant behavior. For example, `decode(allow_error=True)` could cause the function to return None on failure, or return a pair (result, error) like in Go; or `decode(error_value=x)`would cause the function to return the specified default (or sentinel) value x in case of error.

Perhaps the Bazel Starlark folks have opinions here. @brandjon @tetromino

**Comment by tetromino** [comment]
The "starlarky" way would probably be `decode(default=x)` (matching `getattr`, `dict.get`, and `dict.pop`)

A `(result, error)` tuple would be useful if we wanted to propagate the error to the user somehow (via a provider etc.) without failing. Is that something that anyone realistically would need?

**Comment by apeabody** [comment]
Thanks! - Yes it would absolutely be preferable to avoid the duplicate underlying `decode` calls, either the additional decode argument (default value would be preferable) or tuple result would be fantastic for my envisioned use cases.

**Comment by tetromino** [comment]
Corresponding Java Starlark issue: https://github.com/bazelbuild/bazel/issues/18229

**Comment by andreimatei** [comment]
Would there be any appetite from anyone on this thread for also addressing the fallibility of `json.encode()`, in addition to `decode` which so far has been the focus on this conversation and #466 ?
I came here at the suggestion of @adonovan after chatting about it in #467.

`json.encode()` fails in a couple of situations, including:
- circular references
- errors being returned by `HasAttr.Attr(name)`

There are two degrees of resiliency that we could do:
1. do something for `encode` similar to what's being done for `decode`, where an optional arg would tell the function to not return error out, and instead either return some default value, or some other indication of failure that can be recovered. A JSON would not be returned.
2. extend the function (or introduce a new function) to optionally handle or ignore some processing errors, while still returning the partial JSON that could be produced. In particular, I personally care about ignoring errors from `.Attr(name)`, because Delve the Go debugger likes to return such errors from its implementation of `Attr` (the use case is that Delve models variables in a target debug program, and some fields of variables cannot always be read). In such cases, I would still like to get a partial JSON. (for fairness, @adonovan did not seem inclined to add such an option)
